#!/usr/bin/env node
/**
 * Start the site in production.
 *
 * Holds the port with the starting page while Drupal comes up, builds the app
 * against it (the display schemas and decoupled settings are read at build
 * time), then serves pre-rendered pages first and renders the rest live.
 */
const fs = require('fs')
const http = require('http')
const path = require('path')
const { execFileSync, spawn } = require('child_process')
const { deploymentReady, resolveOrigin, waitForBackend } = require('./backend')
const { createHandler, createPageCache, crawl } = require('./page-cache')
const { createArtefacts } = require('./artefacts')
const { createStartingHandler } = require('./starting')

const rootDir = path.join(__dirname, '..')
const env = process.env
const port = Number(env.PORT) || 3000
const host = env.HOST || '0.0.0.0'
const baseUrl = env.DRUXT_BASE_URL || 'http://nginx:8080'
const log = (message) => process.stdout.write(`start: ${message}\n`)

// What the starting page reports until the app takes the port.
const state = { phase: 'waiting', since: new Date().toISOString() }
const setPhase = (phase) => {
  state.phase = phase
  state.since = new Date().toISOString()
}

let handler = createStartingHandler(state)
const server = http.createServer((req, res) => handler(req, res))

const nuxt = (args, extraEnv) =>
  new Promise((resolve, reject) => {
    const bin = path.join(rootDir, 'node_modules', 'nuxt', 'bin', 'nuxt.js')
    const child = spawn(process.execPath, [bin, ...args], { cwd: rootDir, env: { ...env, ...extraEnv }, stdio: 'inherit' })
    child.on('error', reject)
    child.on('exit', (code, signal) =>
      code === 0 ? resolve() : reject(new Error(`nuxt ${args.join(' ')} exited with ${signal || code}`)),
    )
  })

const main = async () => {
  await new Promise((resolve) => server.listen(port, host, resolve))
  log(`starting page on http://${host}:${port}`)

  // Wait for Drupal to report the revision this build is from, so the build
  // never reads the previous release's display configuration. Without a
  // revision of its own, and against a backend with no such endpoint, this
  // falls back to the check it replaces.
  const revision = env.LAGOON_GIT_SHA
  if (revision) log(`waiting for Drupal to finish deploying ${revision}`)
  const ready = await waitForBackend(baseUrl, {
    log,
    ready: (url) => deploymentReady(url, { revision }),
  })
  log(ready ? `Drupal is ready at ${baseUrl}` : `building against ${baseUrl} without waiting further`)
  setPhase('building')

  // Canonical links and share cards name this environment's own origin: the
  // custom route in production, the autogenerated one on previews.
  env.SITE_ORIGIN = resolveOrigin(env) || 'https://druxtjs.org'
  log(`origin: ${env.SITE_ORIGIN}`)

  // The authored pages from Drupal and the generated reference pages, as one
  // corpus. Built once here and held, so the share cards below and the
  // indexes served later describe the same set of pages.
  const artefacts = createArtefacts({
    baseUrl,
    contentDir: path.join(rootDir, 'content'),
    origin: env.SITE_ORIGIN || 'https://druxtjs.org',
    ttl: (Number(env.DOCS_INDEX_TTL) || 300) * 1000,
    log,
  })

  // The machine-readable indexes are served from Drupal now, not written
  // here. A copy left in static/ by an earlier release would be served
  // instead of them, and would describe the pin rather than the site.
  for (const name of ['sitemap.xml', 'llms.txt', 'llms-full.txt']) {
    const stale = path.join(rootDir, 'static', name)
    if (fs.existsSync(stale)) {
      fs.unlinkSync(stale)
      log(`removed the stale ${name} left in static/`)
    }
  }

  // The share cards, as `nuxt generate` writes them. A child process, because
  // satori and resvg crash when required through a patched module loader, so
  // the corpus is handed over as a file rather than in memory.
  try {
    const corpusFile = path.join(rootDir, '.cache', 'corpus.json')
    fs.mkdirSync(path.dirname(corpusFile), { recursive: true })
    fs.writeFileSync(corpusFile, JSON.stringify(await artefacts.corpus()))
    const cards = execFileSync(
      process.execPath,
      [
        path.join(rootDir, 'scripts', 'og-render.js'),
        path.join(rootDir, 'content'),
        path.join(rootDir, 'assets', 'fonts'),
        path.join(rootDir, 'static', 'og'),
        corpusFile,
      ],
      { encoding: 'utf8' },
    )
    log(`rendered ${cards.trim()} share cards`)
  } catch (error) {
    log(`share cards not rendered: ${error.message}`)
  }

  const started = Date.now()
  await nuxt(['build'])
  log(`built in ${Math.round((Date.now() - started) / 1000)}s`)
  setPhase('starting')

  const { loadNuxt } = require('nuxt')
  const app = await loadNuxt({ for: 'start', rootDir })
  const cache =
    env.DOCS_CACHE === '0'
      ? null
      : createPageCache({
          dir: env.DOCS_CACHE_DIR || path.join(rootDir, '.cache', 'pages'),
          ttl: (Number(env.DOCS_CACHE_TTL) || 300) * 1000,
          render: (route) => app.server.renderRoute(route),
          log,
        })
  handler = createHandler({
    cache,
    live: app.render,
    noindex: env.LAGOON_ENVIRONMENT_TYPE !== 'production',
    artefacts,
  })
  log(`serving ${env.SITE_ORIGIN || `http://${host}:${port}`}`)

  if (cache) {
    const warmed = Date.now()
    // Seeded from the same corpus the indexes describe, so a page authored
    // in Drupal is pre-rendered rather than waiting for its first visitor.
    const corpus = await artefacts.corpus().catch(() => [])
    const authored = corpus.map((doc) => doc.route)
    const seeds = ['/', ...new Set([...authored, ...(await app.options.generate.routes())])]
    const { stored, visited } = await crawl({ seeds, store: cache.store })
    log(`pre-rendered ${stored} of ${visited} pages in ${Math.round((Date.now() - warmed) / 1000)}s`)
  }
}

for (const signal of ['SIGINT', 'SIGTERM']) {
  process.on(signal, () => {
    server.close(() => process.exit(0))
    setTimeout(() => process.exit(0), 10000).unref()
  })
}

main().catch(async (error) => {
  process.stderr.write(`start: ${error.stack || error}\n`)
  setPhase('failed')
  // Show the failure for a moment, then exit so the platform restarts us.
  const grace = Number(env.START_FAIL_GRACE || 30) * 1000
  await new Promise((resolve) => setTimeout(resolve, grace))
  process.exit(1)
})
